server:
  port: ${PORT:8761}
  ssl:
    enabled: false
security:
  user:
    password: ${eureka.password}
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  password: ${EUREKA_USER_PASSWORD:password}
